version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: name
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma:
    image: chromadb/chroma
    container_name: chroma-dev
    restart: always
    ports:
      - "8010:8000"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  postgres_data:
  chroma_data:
